# Site settings
title: 'QGUOFENG'  # Your Title
tagline: ''  # A brief tagline for your site
sidebar_image: 

encoding: UTF-8
markdown: kramdown

paginate: 8
paginate_path: "page:num"

#pygments: true
baseurl: ""


# Site settings
name:           
email:          892713852@qq.com
uri:            qguofeng.github.io
github:         http://github.com/qguofeng/qguofeng.github.io
twitter:        
facebook:       
linkedin:       
