# Site settings
title: Modern Blog
description: Modern-Blog A Elegant template for Jekyll
keywords: Modern, Blogging, Fun
author: QGUOFENG
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://github.com/qguofeng/qguofeng.github.io" # the base hostname & protocol for your site
