# Site settings
title: 'QGUOFENG'  # Your Title
tagline: '柔弱、无欲，顺乎自然，但却具有强大的生命力'  # A brief tagline for your site
sidebar_image: /images/cover.jpg

encoding: UTF-8
markdown: kramdown

paginate: 8
paginate_path: "page:num"

#pygments: true
baseurl: ""


# Site settings
name:           
email:          
uri:            qguofeng.github.io
github:         
twitter:        
facebook:       
linkedin:       
